### ISSUE TITLE
Suggestions for your consideration

### ISSUE THREAD

**Issue by Darkmega18** [Daripher/Magic-Totems#2]
Random suggestions and cross compat idea that might be worth a look at for additional effects.

**Danger Totem:** similar to the "Totemic enemies" mod. Totems are spooky looking and are basically wide area spawners that periodically spawn mobs near them. They can be smashed to disable the spawns and would have their own drop loot table to get items out of them upon doing so.

**Combat totem:** When activated it spawns a selection of foes and buffs them with random positive potion effects as if they had used the totem and sets their target to you! After a short while the totem will be interactable like a chest and will drop a loot table of items and go on cooldown or break/become a random normal totem afterwards.

**Curse Totem:** Evil looking totem. Affects you with a curse effect that affects your attributes like armor, max health, speed etc and cannot be purged with milk. Killing a certain amount of hostile mobs or activating a certain amount of other unknown totems with the curse on you dispels the curse and gives you an item from a loot table. Has a much longer cooldown before you can accept another curse from it.

**Totem of Fickle Fate:** it's always random, always mysterious. It doesn't have a cooldown, but consumes some amount of experience points to be used. the more times you use it in quick succession the more randomized buffs and/or debuffs it gives you. Bring milk...

**Waypoint Event Totem:** A reference to Risk of Rain, compatibility with Waystones if it's installed. It's a constant combat totem that spawns as part of a square structure similar to waystones that spawn in villagers. When activated enemies are called to move towards the location of the totem and attack the player, possibly also acting as a danger totem also and spawning additional mobs in a wide area. The player simply has to stay a certain number of blocks close to the totem and it will gradually charge up. 
At certain percentages it might periodically produce effects to players or mobs around it. When the totem finishes the totem destroys itself in a burst of items and is replaced with a waystone to activate for teleportation.

**Eternity Totem:** Cross compat with gateways of eternity if it's installed. Spawns a random small, medium or large gateway of eternity which preserves any effects the original had. https://www.curseforge.com/minecraft/mc-mods/gateways-to-eternity

**Apothic Challenger Totem:** Cross compatibility with Apotheosis, if it's installed. When triggered, spawns a random apotheosis boss mob somewhere nearby using it's own features (loud noise, light beam, highlighted boss, auto targets player) along with an entourage/gang of similar species mobs without buffs.

**Comment by Daripher** [comment]
Thanks for the suggestions, I will certainly add some of these totems in the next update. But this is an issue tracker. If you want to suggest ideas, consider joining discord server (can be found on the curseforge mod page) or leave a comment on the curseforge.

**Comment by Darkmega18** [comment]
you didn't have the forum page that I've seen some github projects have to make it a discussion rather than an issue so I hoped you'd just stick a tag on it or something but anyways. My discord servers are kinda.... full... :V
